### ISSUE TITLE
small screen size all cutted

### ISSUE THREAD

**Issue by istiti** [salesforce-ux/design-system-starter-kit#10]
WOW AWESOME work !

First I want to congratulate you for this awesome work. This started kit is very important for everybody want try fast another UI to their project.

I just have a litle problem with  small screen seems not optimized:
![img_6040](https://cloud.githubusercontent.com/assets/2789203/20743991/aa5ace68-b6d9-11e6-870a-e44ed07853d9.PNG)

**Comment by kaelig** [comment]
Thanks a lot for your feedback, glad it's useful to you!

Small screen optimization requires a bit of manual layout sizing using the [grid system](https://www.lightningdesignsystem.com/components/utilities/grid/#flavor-manual-sizing).

Hope this helps!

**Comment by istiti** [comment]
I think You should for small screen add right class for  full width grid breakpoint when on mobile

**Comment by kaelig** [comment]
Feel free to open a pull request!
