### ISSUE TITLE
Loading SLDS Icons and Styles

### ISSUE THREAD

**Issue by dirajkumar** [salesforce-ux/design-system-starter-kit#15]
Hi, 

I'm new to this and probably missed a step somewhere but I'm having difficulties in loading the styles and icons. Do I need to do anything extra apart from what mentioned in readme? 

This is what I see. 

<img width="947" alt="screen shot 2017-01-30 at 3 46 16 pm" src="https://cloud.githubusercontent.com/assets/1153390/22441013/9e74bf78-e703-11e6-8f79-536c1fdacb75.png">

Thanks in advance!
Diraj

**Comment by kaelig** [comment]
Thank you very much @dirajkumar for using the starter kit and flagging this issue.

Looks like a bug with node-sass - which could be related to https://github.com/sass/node-sass/issues/1876

Apologies for the trouble, I've pushed a fix - `npm install` and you should be all set.

**Comment by dirajkumar** [comment]
@kaelig Awesome! Thanks for the quick response..
