### ISSUE TITLE
Supply an optional templating language

### ISSUE THREAD

**Issue by kaelig** [salesforce-ux/design-system-starter-kit#2]
Twig seems like a great candidate: http://twig.sensiolabs.org/documentation

And we could use gulp-twig for that. https://www.npmjs.com/package/gulp-twig

A v2 of this feature could include gulp-data that allows developers to plug JSON data onto their templates: https://www.npmjs.com/package/gulp-data

Thanks to @jina for suggesting this feature.

**Comment by jina** [comment]
yeah, writing straight html is kinda painful. just used it for the diff tool and it took me longer than i'd like to make stuff. templating would be rad.

**Comment by kaelig** [comment]
Just discovered nunjucks which might be better for this use case: https://mozilla.github.io/nunjucks/

**Comment by bekos** [comment]
You should definitely consider Jade (renamed to Pug) as an option :-)
https://strongloop.com/strongblog/compare-javascript-templates-jade-mustache-dust/

**Comment by kaelig** [comment]
I love Pug but I'd like to stay as close as possible to HTML so users don't have to learn a whole new language and can easily copy-paste markup examples from www.lightningdesignsystem.com.

**Comment by kaelig** [comment]
Oh and thanks for proposing a PR! Feel free to fork the Starter Kit and make it work with Jade if that suits your needs.

**Comment by kaelig** [comment]
I've just added support for Nunjucks templates, with data injection from json files. Enjoy!
