### ISSUE TITLE
Source maps referring to compiled Scss not source Scss

### ISSUE THREAD

**Issue by tyrollins** [salesforce-ux/design-system-starter-kit#9]
I have been tinkering with the starter kit and have run into a problem with source maps. The source maps are created via the gulp task just fine, however, they refer to the compiled CSS rather than the source Sass. Is this by design? It would seem to be more useful with source maps referring to the source Sass. 

I'm absolutely terrible with Gulp, so any help correcting this so the source maps refer to source Sass would be pretty awesome. 

Cheers.

**Comment by kaelig** [comment]
Thanks for using the starter kit!

Sourcemaps do refer to the source files, not sure what's happening in your case.

See this screenshot of what I get when I inspect the top bar of the [example.html](https://starter-kit-demo.herokuapp.com/example.html) page:
![screenshot 2016-11-30 18 21 51](https://cloud.githubusercontent.com/assets/85783/20779529/e4aa0598-b729-11e6-9554-dfe3d46954f9.png)

It might be a Chrome config issue?

**Comment by kaelig** [comment]
Closing this as it's not been answered in 5 weeks.
